apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    component: otel-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
  - name: grpc 
    port: 4317
  selector:
    component: otel-collector