apiVersion: v1
kind: Service
metadata:
  name: otel-collector
  labels:
    app: otel-collector
    component: otel-collector
spec:
  ports:
  - name: metrics # Default endpoint for querying metrics.
    port: 8888
    targetPort: 8888
  - name: jaeger 
    port: 14268
  selector:
    app: otel-collector